---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: Install apache packages 
    yum:
      name: apache2
      state: present
  - name: Open port 80 for http access
    shell: ufw enable 'Apache Full'
